### ISSUE TITLE
when the jessibuca used in vue3 with typescript , it doesn't work.

### ISSUE THREAD

**Issue by dualven** [langhuihui/H5RtmpClient#137]
(1) when it is used in vue3 with typescript , there is a error : 
![e800fb3211e25cdd3ebeda373ef8fe3](https://user-images.githubusercontent.com/2209534/155277737-33b71ec9-9fac-4dc1-991b-907ad84147b8.png)
(2) then , I  use it with jessibuca.d.ts , I import it , and new Jessibuca.Jessibuca(), it says:
 "can't use name space as a value" , is the jessibuca.js not compatible with the  jessibuca.d.ts? 
![efa5b3022e8655facfc8a94e9f582dc](https://user-images.githubusercontent.com/2209534/155278077-dc9dfe1e-dd06-40bd-b67e-40e9912563c1.png)

would you please help me to resolve this problem?

**Comment by BlackTeaLeaf** [comment]
d.ts 的问题我会比较建议官方使用这个版本
#133

因为 Jessibuca 的建构子暴露在 window 底下
所以可以直接使用 new Jessibuca() 进行建构

但是 d.ts 的定义变成得改写成
```typescript
// @ts-expect-error
this._player = new Jessibuca( ) as Jessibuca.Jessibuca
// @ts-expect-error
this._player = new ( Jessibuca as Jessibuca.JessibucaConstructor )( )
```
并不是很直觉

而且会引发 ts(2708) 的错误
![image](https://user-images.githubusercontent.com/23370842/155286754-384033b7-950e-4fa7-b41f-023fcc9c1067.png)


new Jessibuca.Jessibuca() 明显是不正确，因为 Jessibuca.js 并没有暴露 Jessibuca.Jessibuca 这个建构子

-------
--This paragraph is a translation--

For the problem of d.ts, I would recommend the official use of this version
#133

Because Jessibuca's constructor is exposed under the window
So it can be constructed directly using new Jessibuca()

But the definition of d.ts becomes rewritten as
```typescript
// @ts-expect-error
this._player = new Jessibuca( ) as Jessibuca.Jessibuca
// @ts-expect-error
this._player = new( Jessibuca as Jessibuca.JessibucaConstructor )( )
````
not very intuitive

And it throws an error of ts(2708)
![image](https://user-images.githubusercontent.com/23370842/155286754-384033b7-950e-4fa7-b41f-023fcc9c1067.png)


new Jessibuca.Jessibuca() is obviously incorrect, because Jessibuca.js does not expose the constructor Jessibuca.Jessibuca

**Comment by bosscheng** [comment]
@BlackTeaLeaf 看到你提交的PR了，已合并过去了。

**Comment by BlackTeaLeaf** [comment]
@bosscheng 
感谢，我又发现一点小错误，又更正了一下
#138

**Comment by dualven** [comment]
感谢大家，可以用了！！@BlackTeaLeaf @bosscheng @BlackTeaLeaf

**Comment by chenparty** [comment]
请问下各位大佬，最新版本下，我这么import的，会报错
![image](https://user-images.githubusercontent.com/16755257/157808645-987c7a75-6529-4711-adab-ecf3cfffd72d.png)

![image](https://user-images.githubusercontent.com/16755257/157808624-abec7b5b-c2c4-45e0-aaad-4488494993bf.png)

**Comment by bosscheng** [comment]
@chenparty 看下https://jessibuca.com/demo.html

**Comment by BlackTeaLeaf** [comment]
@chenparty  
Jessibuca 应该没有支援 ecma module 或 commonJS module 
所以你不能使用 import 的方式引入
必须在 html 的 head 透过 script 引入脚本
或者透过 js 来执行上面的动作

html 载入脚本后，Jessibuca 是全域对象
